Name: Lama Alfreah.

# M4.Ex1: Housing Prices Model (PyCaret)

- Run: [**Open In Colab**](https://colab.research.google.com/github/HassanAlgoz/B5/blob/main/content/W3/M6/exercises/ex1_pycaret_regression.ipynb)

## Exercise

Your task is to follow the steps outlined here, and apply them on the **California Housing Dataset** below:

- [**🚀 Regression**](https://pycaret.gitbook.io/docs/get-started/quickstart#regression)
    - Setup
    - Compare Models
    - Analyze Model
    - Predictions
    - Save the model

## California Housing Prices Dataset


Find and download the dataset from Kaggle at [California Housing Dataset](https://www.kaggle.com/datasets/dhirajnirne/california-housing-data).

According to [keras.io](https://keras.io/api/datasets/california_housing/):

> This dataset was obtained from the StatLib repository.
>
> It's a continuous regression dataset with 20,640 samples with 8 features each.
>
> The target variable is a scalar: the median house value for California districts, in dollars.
>
> The 8 input features are the following:
>
> - MedInc: median income in block group
> - HouseAge: median house age in block group
> - AveRooms: average number of rooms per household
> - AveBedrms: average number of bedrooms per household
> - Population: block group population
> - AveOccup: average number of household members
> - Latitude: block group latitude
> - Longitude: block group longitude
>
> This dataset was derived from the 1990 U.S. census, using one row per census block group. A block group is the smallest geographical unit for which the U.S. Census Bureau publishes sample data (a block group typically has a population of 600 to 3,000 people).
>
> A household is a group of people residing within a home. Since the average number of rooms and bedrooms in this dataset are provided per household, these columns may take surprisingly large values for block groups with few households and many empty houses, such as vacation resorts.

### Load the data

In [1]:
import pandas as pd
import kagglehub
from kagglehub import KaggleDatasetAdapter
# Set the path to the file you'd like to load
file_path = "housing.csv"
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "dhirajnirne/california-housing-data",
  file_path,
)
df.head()

/var/folders/19/p6cn2wf124s6yxbb3kn3wwy40000gn/T/ipykernel_27697/3672944266.py:6: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

**Task**: Your model should learn from this data and be able to predict the median housing price (`median_house_value`) in any district, given all the other metrics.

Please read the above dataset description to understand what the features mean.

### Spilt the data

In [2]:
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(
    df, test_size=0.2, random_state=42
)

### Training

In [3]:
from autogluon import *

from autogluon.tabular import TabularPredictor

predictor = TabularPredictor( label= 'median_house_value' ).fit(
    train_data= train_data,
    presets='medium_quality_faster_train',
    time_limit= 60,
    excluded_model_types = ['NN_TORCH', 'FASTI'],
    num_cpus= 1,
    ag_args_fit ={'num_gpus' : 0}
)

No path specified. Models will be saved in: "AutogluonModels/ag-20260422_081408"
Preset alias specified: 'medium_quality_faster_train' maps to 'medium_quality'.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.13.5
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.3.0: Wed Jan 28 20:48:41 PST 2026; root:xnu-12377.81.4~5/RELEASE_ARM64_T6041
CPU Count:          14
Pytorch Version:    2.9.1
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       12.55 GB / 36.00 GB (34.9%)
Disk Space Avail:   363.32 GB / 926.35 GB (39.2%)
===================================================
Presets specified: ['medium_quality_faster_train']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "/Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_081408"
Train Data Rows:    16512
Train Data Columns: 9
Label Column:       median_house_value
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (500001.0, 14999.0, 207194.69374, 115622.62645)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    12855.24 MB
	Train Data (Original)  Memory Usage: 1.91 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 8 | ['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', ...]
		('object', []) : 1 | ['ocean_proximity']
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) : 1 | ['ocean_proximity']
		('float', [])    : 8 | ['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', ...]
	0.0s = Fit runtime
	9 features in original data used to generate 9 features in processed data.
	Train Data (Processed) Memory Usage: 1.02 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.05s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 14860, Val Rows: 1652
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Excluded models: ['NN_TORCH'] (Specified by `excluded_model_types`)
Fitting 8 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ... Training model for up to 59.95s of the 59.95s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/12.5 GB

[1000]	valid_set's rmse: 49409.6
[2000]	valid_set's rmse: 48518.2
[3000]	valid_set's rmse: 48360
[4000]	valid_set's rmse: 48312.8
[5000]	valid_set's rmse: 48307.8

	-48253.7613	 = Validation score   (-root_mean_squared_error)
	2.48s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 57.40s of the 57.40s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/12.5 GB
	-45803.2746	 = Validation score   (-root_mean_squared_error)
	0.65s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE ... Training model for up to 56.73s of the 56.73s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.1/12.4 GB

[1000]	valid_set's rmse: 45813.7

	-50139.408	 = Validation score   (-root_mean_squared_error)
	4.32s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 52.32s of the 52.32s of remaining time.
	Fitting with cpus=1, gpus=0
	-43578.5712	 = Validation score   (-root_mean_squared_error)
	47.85s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesMSE ... Training model for up to 4.46s of the 4.46s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.1/11.4 GB
	-53235.5527	 = Validation score   (-root_mean_squared_error)
	0.92s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 3.32s of the 3.32s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/11.2 GB
	-52380.2538	 = Validation score   (-root_mean_squared_error)
	3.07s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.95s of the 0.23s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=1, gpus=0, mem=0.0/11.2 GB
	Ensemble Weights: {'CatBoost': 0.84, 'RandomForestMSE': 0.12, 'LightGBM': 0.04}
	-43403.1762	 = Validation score   (-root_mean_squared_error)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 59.78s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 44383.3 rows/s (1652 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_081408")

### Monitoring

In [4]:
predictor. leaderboard()

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,-43403.176158,root_mean_squared_error,0.037221,52.816003,0.000108,0.003197,2,True,7
1,CatBoost,-43578.571157,root_mean_squared_error,0.003261,47.850435,0.003261,47.850435,1,True,4
2,LightGBM,-45803.274648,root_mean_squared_error,0.008491,0.645249,0.008491,0.645249,1,True,2
3,LightGBMXT,-48253.761251,root_mean_squared_error,0.033397,2.478987,0.033397,2.478987,1,True,1
4,RandomForestMSE,-50139.408027,root_mean_squared_error,0.025361,4.317123,0.025361,4.317123,1,True,3
5,NeuralNetFastAI,-52380.253845,root_mean_squared_error,0.007028,3.068317,0.007028,3.068317,1,True,6
6,ExtraTreesMSE,-53235.552737,root_mean_squared_error,0.026364,0.917209,0.026364,0.917209,1,True,5

In [5]:
predictor.fit_summary(show_plot=True, verbosity=2)

*** Summary of fit() ***
Estimated performance of each model:
                 model     score_val              eval_metric  pred_time_val   fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0  WeightedEnsemble_L2 -43403.176158  root_mean_squared_error       0.037221  52.816003                0.000108           0.003197            2       True          7
1             CatBoost -43578.571157  root_mean_squared_error       0.003261  47.850435                0.003261          47.850435            1       True          4
2             LightGBM -45803.274648  root_mean_squared_error       0.008491   0.645249                0.008491           0.645249            1       True          2
3           LightGBMXT -48253.761251  root_mean_squared_error       0.033397   2.478987                0.033397           2.478987            1       True          1
4      RandomForestMSE -50139.408027  root_mean_squared_error       0.025361   4.317123                0.025361           4.317123            1       True          3
5      NeuralNetFastAI -52380.253845  root_mean_squared_error       0.007028   3.068317                0.007028           3.068317            1       True          6
6        ExtraTreesMSE -53235.552737  root_mean_squared_error       0.026364   0.917209                0.026364           0.917209            1       True          5
Number of models trained: 7
Types of models trained:
{'CatBoostModel', 'LGBModel', 'NNFastAiTabularModel', 'XTModel', 'WeightedEnsembleModel', 'RFModel'}
Bagging used: False
Multi-layer stack-ensembling used: False
Feature Metadata (Processed):
(raw dtype, special dtypes):
('category', []) : 1 | ['ocean_proximity']
('float', [])    : 8 | ['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', ...]
Plot summary of models saved to file: /Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_081408/SummaryOfModels.html
*** End of fit() summary ***

{'model_types': {'LightGBMXT': 'LGBModel',
  'LightGBM': 'LGBModel',
  'RandomForestMSE': 'RFModel',
  'CatBoost': 'CatBoostModel',
  'ExtraTreesMSE': 'XTModel',
  'NeuralNetFastAI': 'NNFastAiTabularModel',
  'WeightedEnsemble_L2': 'WeightedEnsembleModel'},
 'model_performance': {'LightGBMXT': np.float64(-48253.76125100566),
  'LightGBM': np.float64(-45803.27464822096),
  'RandomForestMSE': np.float64(-50139.40802685508),
  'CatBoost': np.float64(-43578.57115660869),
  'ExtraTreesMSE': np.float64(-53235.55273688137),
  'NeuralNetFastAI': np.float64(-52380.25384519905),
  'WeightedEnsemble_L2': np.float64(-43403.17615825185)},
 'model_best': 'WeightedEnsemble_L2',
 'model_paths': {'LightGBMXT': ['LightGBMXT'],
  'LightGBM': ['LightGBM'],
  'RandomForestMSE': ['RandomForestMSE'],
  'CatBoost': ['CatBoost'],
  'ExtraTreesMSE': ['ExtraTreesMSE'],
  'NeuralNetFastAI': ['NeuralNetFastAI'],
  'WeightedEnsemble_L2': ['WeightedEnsemble_L2']},
 'model_fit_times': {'LightGBMXT': 2.478986978530884,
  'LightGBM': 0.6452486515045166,
  'RandomForestMSE': 4.317122936248779,
  'CatBoost': 47.85043478012085,
  'ExtraTreesMSE': 0.9172091484069824,
  'NeuralNetFastAI': 3.06831693649292,
  'WeightedEnsemble_L2': 0.0031969547271728516},
 'model_pred_times': {'LightGBMXT': 0.03339695930480957,
  'LightGBM': 0.008491039276123047,
  'RandomForestMSE': 0.025360822677612305,
  'CatBoost': 0.0032613277435302734,
  'ExtraTreesMSE': 0.02636432647705078,
  'NeuralNetFastAI': 0.007027864456176758,
  'WeightedEnsemble_L2': 0.00010800361633300781},
 'num_bag_folds': 0,
 'max_stack_level': 2,
 'model_hyperparams': {'LightGBMXT': {'learning_rate': 0.05,
   'extra_trees': True,
   'seed': 0},
  'LightGBM': {'learning_rate': 0.05, 'seed': 0},
  'RandomForestMSE': {'n_estimators': 300,
   'max_leaf_nodes': 15000,
   'n_jobs': -1,
   'bootstrap': True,
   'criterion': 'squared_error',
   'random_state': 0},
  'CatBoost': {'iterations': 10000,
   'learning_rate': 0.05,
   'allow_writing_files': False,
   'eval_metric': 'RMSE',
   'random_seed': 0},
  'ExtraTreesMSE': {'n_estimators': 300,
   'max_leaf_nodes': 15000,
   'n_jobs': -1,
   'bootstrap': True,
   'criterion': 'squared_error',
   'random_state': 0},
  'NeuralNetFastAI': {'layers': None,
   'emb_drop': 0.1,
   'ps': 0.1,
   'bs': 'auto',
   'lr': 0.01,
   'epochs': 'auto',
   'early.stopping.min_delta': 0.0001,
   'early.stopping.patience': 20,
   'smoothing': 0.0,
   'random_seed': 0},
  'WeightedEnsemble_L2': {'use_orig_features': False,
   'valid_stacker': True,
   'max_base_models': 0,
   'max_base_models_per_type': 'auto',
   'save_bag_folds': True,
   'stratify': 'auto',
   'bin': 'auto',
   'n_bins': None,
   'vary_seed_across_folds': False,
   'model_random_seed': 0}},
 'leaderboard':                  model     score_val              eval_metric  pred_time_val  \
 0  WeightedEnsemble_L2 -43403.176158  root_mean_squared_error       0.037221
 1             CatBoost -43578.571157  root_mean_squared_error       0.003261
 2             LightGBM -45803.274648  root_mean_squared_error       0.008491
 3           LightGBMXT -48253.761251  root_mean_squared_error       0.033397
 4      RandomForestMSE -50139.408027  root_mean_squared_error       0.025361
 5      NeuralNetFastAI -52380.253845  root_mean_squared_error       0.007028
 6        ExtraTreesMSE -53235.552737  root_mean_squared_error       0.026364

     fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  \
 0  52.816003                0.000108           0.003197            2
 1  47.850435                0.003261          47.850435            1
 2   0.645249                0.008491           0.645249            1
 3   2.478987                0.033397           2.478987            1
 4   4.317123                0.025361           4.317123            1
 5   3.068317                0.007028           3.068317            1
 6   0.917209                0.026364           0.917209            1

    can_infer  fit_order
 0       True          7
 1       True          4
 2       True          2
 3       True          1
 4       True          3
 5       True          6
 6       True          5  }

In [6]:
predictor.feature_importance(test_data)

Computing feature importance via permutation shuffling for 9 features using 4128 rows with 5 shuffle sets...
	9.13s	= Expected runtime (1.83s per shuffle set)
	2.1s	= Actual runtime (Completed 5 of 5 shuffle sets)

,importance,stddev,p_value,n,p99_high,p99_low
longitude,112885.174262,1545.666556,4.216851e-09,5,116067.723064,109702.625461
latitude,103612.596102,1477.295827,4.957734e-09,5,106654.368628,100570.823575
total_rooms,44951.609088,486.126248,1.641077e-09,5,45952.549751,43950.668425
median_income,28493.018198,520.023973,1.330847e-08,5,29563.754745,27422.281651
population,18458.023094,568.956383,1.081948e-07,5,19629.512151,17286.534038
total_bedrooms,12706.540128,926.884952,3.373653e-06,5,14615.009054,10798.071202
ocean_proximity,10652.040396,211.388419,1.860145e-08,5,11087.292072,10216.788720
households,9088.925206,533.206666,1.414891e-06,5,10186.805102,7991.045310
housing_median_age,4071.285154,387.518720,9.731904e-06,5,4869.191553,3273.378754

### Predicting

In [7]:
# Predict for each row
predictor.predict(test_data)

20046    265740.281250
3024     316656.625000
15663    730809.125000
20484    492734.937500
9814     447359.812500
             ...
15362    232466.312500
16623    221301.281250
18086    489722.687500
2144      68937.687500
3665     175150.734375
Name: median_house_value, Length: 4128, dtype: float32

In [8]:
# Evaluate various metrics, it needs test_data to have the label column
predictor.evaluate(test_data)

/Users/lamaalfreah/Desktop/AAI/.venv/lib/python3.13/site-packages/scipy/stats/_stats_py.py:4776: RuntimeWarning: overflow encountered in vecdot
  r = xp.vecdot(xm / normxm, ym / normym, axis=axis)

{'root_mean_squared_error': np.float64(-60703.58823605448),
 'mean_squared_error': -3684925624.7324514,
 'mean_absolute_error': -36000.62072470022,
 'r2': 0.718795758734871,
 'pearsonr': 0.860716305856677,
 'median_absolute_error': -19123.953125}

In [9]:
# Get a list of string names
models = predictor.model_names()

In [10]:
# Predict with the 2nd model. Both predict_proba and evaluate also accept the model argument
predictor.predict(test_data, model=models[1])

20046     34306.277344
3024      67246.296875
15663    461673.000000
20484    253537.718750
9814     248888.234375
             ...
15362    230801.234375
16623    217382.562500
18086    488676.875000
2144      79184.859375
3665     165561.156250
Name: median_house_value, Length: 4128, dtype: float32

### Deploying

In [16]:
# Load saved model from disk.
predictor = TabularPredictor.load('AutogluonModels/ag-20260422_081408/')

In [19]:
predictor.persist()
presets=['good_quality', 'optimize_for_deployment']

The following 4 models were already persisted and will be ignored in the model loading process: ['CatBoost', 'RandomForestMSE', 'LightGBM', 'WeightedEnsemble_L2']
No valid unpersisted models were specified to be persisted, so no change in model persistence was performed.

In [20]:
# Will create a minimal artifact for deployment.
predictor.clone_for_deployment(path='prod_model_dir')
# Load the optimized predictor and persist models in mem.
predictor_opt = TabularPredictor.load('prod_model_dir')
predictor_opt.persist()
predictions = predictor_opt.predict(test_data)

Cloned TabularPredictor located in '/Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_081408' to 'prod_model_dir'.
	To load the cloned predictor: predictor_clone = TabularPredictor.load(path="prod_model_dir")
Clone: Keeping minimum set of models required to predict with best model 'WeightedEnsemble_L2'...
Deleting model LightGBMXT. All files under /Users/lamaalfreah/Desktop/AAI/student/c3/prod_model_dir/models/LightGBMXT will be removed.
Deleting model ExtraTreesMSE. All files under /Users/lamaalfreah/Desktop/AAI/student/c3/prod_model_dir/models/ExtraTreesMSE will be removed.
Deleting model NeuralNetFastAI. All files under /Users/lamaalfreah/Desktop/AAI/student/c3/prod_model_dir/models/NeuralNetFastAI will be removed.
Clone: Removing artifacts unnecessary for prediction. NOTE: Clone can no longer fit new models, and most functionality except for predict and predict_proba will no longer work
Persisting 4 models in memory. Models will require 3.4% of memory.