Name: Lama Alfreah.

# M4.Ex2: Penguins Classification (PyCaret)

- Run: [**Open In Colab**](https://colab.research.google.com/github/HassanAlgoz/B5/blob/main/content/W3/M6/exercises/ex2_pycaret_classification.ipynb)

## Exercise

Your task is to follow the steps outlined here, and apply them on the **Palmer Penguins Dataset** below:

- [**🚀 Classification**](https://pycaret.gitbook.io/docs/get-started/quickstart#classification)
    - Setup
    - Compare Models
    - Analyze Model
    - Predictions
    - Save the model

## Palmer Penguins Dataset

The goal of palmer penguins is to provide a great dataset for data exploration & visualization, as an alternative to iris.

The data contains 344 penguins. There are 3 different species of penguins in this dataset, collected from 3 islands in the Palmer Archipelago, Antarctica.

- Features: `4` numerical, `2` categorical
- Target: `species` (Categorical / 3 classes)
- Size: `344` samples
- Source: [Palmer Penguins](https://allisonhorst.github.io/palmerpenguins/)

### Load the data

In [2]:
import seaborn as sns

penguins = sns.load_dataset('penguins')
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

## Experiments

1. **First experiment**:
    - X = Flipper Length (numerical) & Bill Length (numerical)
    - y = Species (categorical)
2. **Second experiment**:
    - X = Weights (numerical) & Species (categorical)
    - y = Sex (categroical)
3. **Third experiment**:
    - X = `island`, `bill_length_mm`, `bill_depth_mm`, `flipper_length_mm`, `body_mass_g`
    - y = Sex and Species (multi-label classification)

### Training

### First experiment

In [ ]:
from autogluon import *

from autogluon.tabular import TabularPredictor
exp1_data = penguins[["flipper_length_mm", "bill_length_mm", "species"]]

predictor_exp1 = TabularPredictor(
    label="species",
    problem_type="multiclass",
    eval_metric="accuracy"
).fit(
    exp1_data,
    presets='medium_quality_faster_train',
    time_limit= 60,
    excluded_model_types = ['NN_TORCH', 'FASTI'],
    num_cpus= 1,
    ag_args_fit ={'num_gpus' : 0}
)

No path specified. Models will be saved in: "AutogluonModels/ag-20260422_083253"
Preset alias specified: 'medium_quality_faster_train' maps to 'medium_quality'.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.13.5
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.3.0: Wed Jan 28 20:48:41 PST 2026; root:xnu-12377.81.4~5/RELEASE_ARM64_T6041
CPU Count:          14
Pytorch Version:    2.9.1
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       11.31 GB / 36.00 GB (31.4%)
Disk Space Avail:   362.17 GB / 926.35 GB (39.1%)
===================================================
Presets specified: ['medium_quality_faster_train']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "/Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_083253"
Train Data Rows:    344
Train Data Columns: 2
Label Column:       species
Problem Type:       multiclass
Preprocessing data ...
Train Data Class Count: 3
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    11572.57 MB
	Train Data (Original)  Memory Usage: 0.01 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 2 | ['flipper_length_mm', 'bill_length_mm']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 2 | ['flipper_length_mm', 'bill_length_mm']
	0.0s = Fit runtime
	2 features in original data used to generate 2 features in processed data.
	Train Data (Processed) Memory Usage: 0.01 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.01s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 275, Val Rows: 69
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Excluded models: ['NN_TORCH'] (Specified by `excluded_model_types`)
Fitting 10 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetFastAI ... Training model for up to 59.99s of the 59.99s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/11.3 GB
No improvement since epoch 3: early stopping
	0.942	 = Validation score   (accuracy)
	0.34s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 59.64s of the 59.64s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/11.3 GB
	0.942	 = Validation score   (accuracy)
	0.12s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 59.52s of the 59.52s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/11.3 GB
	0.9565	 = Validation score   (accuracy)
	0.09s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 59.42s of the 59.42s of remaining time.
	Fitting with cpus=1, gpus=0
	0.9565	 = Validation score   (accuracy)
	0.2s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 59.20s of the 59.20s of remaining time.
	Fitting with cpus=1, gpus=0
	0.9565	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 59.04s of the 59.04s of remaining time.
	Fitting with cpus=1, gpus=0
	0.9565	 = Validation score   (accuracy)
	0.19s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 58.85s of the 58.85s of remaining time.
	Fitting with cpus=1, gpus=0
	0.942	 = Validation score   (accuracy)
	0.13s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 58.70s of the 58.70s of remaining time.
	Fitting with cpus=1, gpus=0
	0.942	 = Validation score   (accuracy)
	0.15s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 58.54s of the 58.54s of remaining time.
	Fitting with cpus=1, gpus=0
	0.9565	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 58.50s of the 58.50s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.2/11.3 GB
	0.9565	 = Validation score   (accuracy)
	0.15s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.99s of the 58.35s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=1, gpus=0, mem=0.0/11.3 GB
	Ensemble Weights: {'LightGBM': 1.0}
	0.9565	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1.68s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 105238.9 rows/s (69 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_083253")

### Second experiment

In [6]:
exp2_data = penguins[["body_mass_g", "species", "sex"]].dropna()

predictor_exp2 = TabularPredictor(
    label="sex",
    problem_type="binary",
    eval_metric="accuracy"
).fit(
    exp2_data,
    presets='medium_quality_faster_train',
    time_limit= 60,
    excluded_model_types = ['NN_TORCH', 'FASTI'],
    num_cpus= 1,
    ag_args_fit ={'num_gpus' : 0}
)

pred_exp2 = predictor_exp2.predict(exp2_data.drop(columns=["sex"]))
predictor_exp2.leaderboard(exp2_data, silent=True)

No path specified. Models will be saved in: "AutogluonModels/ag-20260422_084145"
Preset alias specified: 'medium_quality_faster_train' maps to 'medium_quality'.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.13.5
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.3.0: Wed Jan 28 20:48:41 PST 2026; root:xnu-12377.81.4~5/RELEASE_ARM64_T6041
CPU Count:          14
Pytorch Version:    2.9.1
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       10.33 GB / 36.00 GB (28.7%)
Disk Space Avail:   361.06 GB / 926.35 GB (39.0%)
===================================================
Presets specified: ['medium_quality_faster_train']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "/Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_084145"
Train Data Rows:    333
Train Data Columns: 2
Label Column:       sex
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = Male, class 0 = Female
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (Male) vs negative (Female) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10640.55 MB
	Train Data (Original)  Memory Usage: 0.02 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 1 | ['body_mass_g']
		('object', []) : 1 | ['species']
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) : 1 | ['species']
		('float', [])    : 1 | ['body_mass_g']
	0.0s = Fit runtime
	2 features in original data used to generate 2 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.02s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 266, Val Rows: 67
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Excluded models: ['NN_TORCH'] (Specified by `excluded_model_types`)
Fitting 10 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ... Training model for up to 59.98s of the 59.98s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/10.4 GB
	0.9104	 = Validation score   (accuracy)
	0.09s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 59.89s of the 59.89s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/10.4 GB
	0.9104	 = Validation score   (accuracy)
	0.08s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 59.80s of the 59.80s of remaining time.
	Fitting with cpus=1, gpus=0
	0.7761	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 59.64s of the 59.64s of remaining time.
	Fitting with cpus=1, gpus=0
	0.7761	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 59.48s of the 59.48s of remaining time.
	Fitting with cpus=1, gpus=0
	0.9254	 = Validation score   (accuracy)
	0.2s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 59.28s of the 59.28s of remaining time.
	Fitting with cpus=1, gpus=0
	0.7761	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 59.12s of the 59.12s of remaining time.
	Fitting with cpus=1, gpus=0
	0.7761	 = Validation score   (accuracy)
	0.13s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 58.97s of the 58.97s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/10.4 GB
	0.8806	 = Validation score   (accuracy)
	0.11s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 58.85s of the 58.85s of remaining time.
	Fitting with cpus=1, gpus=0
	0.8358	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 58.82s of the 58.82s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.1/10.4 GB
	0.8358	 = Validation score   (accuracy)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.98s of the 58.72s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=1, gpus=0, mem=0.0/10.4 GB
	Ensemble Weights: {'CatBoost': 1.0}
	0.9254	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1.31s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 87653.9 rows/s (67 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (67 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_084145")

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,XGBoost,0.873874,0.835821,accuracy,0.003257,0.001282,0.023702,0.003257,0.001282,0.023702,1,True,9
1,ExtraTreesEntr,0.870871,0.776119,accuracy,0.015744,0.014822,0.132289,0.015744,0.014822,0.132289,1,True,7
2,RandomForestEntr,0.870871,0.776119,accuracy,0.017303,0.014987,0.135269,0.017303,0.014987,0.135269,1,True,4
3,ExtraTreesGini,0.870871,0.776119,accuracy,0.027498,0.012577,0.137636,0.027498,0.012577,0.137636,1,True,6
4,RandomForestGini,0.870871,0.776119,accuracy,0.028923,0.014696,0.139628,0.028923,0.014696,0.139628,1,True,3
5,CatBoost,0.867868,0.925373,accuracy,0.000905,0.000516,0.200601,0.000905,0.000516,0.200601,1,True,5
6,LightGBM,0.867868,0.910448,accuracy,0.001020,0.000649,0.084456,0.001020,0.000649,0.084456,1,True,2
7,WeightedEnsemble_L2,0.867868,0.925373,accuracy,0.001391,0.000764,0.218758,0.000486,0.000248,0.018157,2,True,11
8,LightGBMLarge,0.858859,0.835821,accuracy,0.000738,0.000653,0.098963,0.000738,0.000653,0.098963,1,True,10
9,LightGBMXT,0.855856,0.910448,accuracy,0.000909,0.000636,0.093488,0.000909,0.000636,0.093488,1,True,1
10,NeuralNetFastAI,0.831832,0.880597,accuracy,0.004572,0.002375,0.109723,0.004572,0.002375,0.109723,1,True,8

### Third experiment

In [8]:
exp3_sex = penguins[[
    "island", "bill_length_mm", "bill_depth_mm",
    "flipper_length_mm", "body_mass_g", "sex"
]].dropna()

predictor_exp3_sex = TabularPredictor(
    label="sex",
    problem_type="binary",
    eval_metric="accuracy"
).fit(exp3_sex)

exp3_species = penguins[[
    "island", "bill_length_mm", "bill_depth_mm",
    "flipper_length_mm", "body_mass_g", "species"
]]

predictor_exp3_species = TabularPredictor(
    label="species",
    problem_type="multiclass",
    eval_metric="accuracy"
).fit(exp3_species)

No path specified. Models will be saved in: "AutogluonModels/ag-20260422_085705"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.13.5
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.3.0: Wed Jan 28 20:48:41 PST 2026; root:xnu-12377.81.4~5/RELEASE_ARM64_T6041
CPU Count:          14
Pytorch Version:    2.9.1
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       11.15 GB / 36.00 GB (31.0%)
Disk Space Avail:   362.14 GB / 926.35 GB (39.1%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_085705"
Train Data Rows:    333
Train Data Columns: 5
Label Column:       sex
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = Male, class 0 = Female
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (Male) vs negative (Female) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    11382.36 MB
	Train Data (Original)  Memory Usage: 0.03 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 4 | ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']
		('object', []) : 1 | ['island']
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) : 1 | ['island']
		('float', [])    : 4 | ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']
	0.0s = Fit runtime
	5 features in original data used to generate 5 features in processed data.
	Train Data (Processed) Memory Usage: 0.01 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.02s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 266, Val Rows: 67
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Fitting with cpus=14, gpus=0, mem=0.0/11.1 GB
	0.9254	 = Validation score   (accuracy)
	0.45s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	Fitting with cpus=14, gpus=0, mem=0.0/11.1 GB
	0.9403	 = Validation score   (accuracy)
	0.79s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	Fitting with cpus=14, gpus=0
	0.9254	 = Validation score   (accuracy)
	0.13s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestEntr ...
	Fitting with cpus=14, gpus=0
	0.9104	 = Validation score   (accuracy)
	0.12s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: CatBoost ...
	Fitting with cpus=14, gpus=0
	0.9254	 = Validation score   (accuracy)
	0.26s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	Fitting with cpus=14, gpus=0
	0.9254	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	Fitting with cpus=14, gpus=0
	0.9254	 = Validation score   (accuracy)
	0.13s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Fitting with cpus=14, gpus=0, mem=0.0/11.1 GB
No improvement since epoch 9: early stopping
	0.9104	 = Validation score   (accuracy)
	0.15s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: XGBoost ...
	Fitting with cpus=14, gpus=0
	0.9254	 = Validation score   (accuracy)
	0.45s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	Fitting with cpus=14, gpus=0, mem=0.0/11.1 GB
/Users/lamaalfreah/Desktop/AAI/.venv/lib/python3.13/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	0.9254	 = Validation score   (accuracy)
	2.07s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Fitting with cpus=14, gpus=0, mem=0.1/11.0 GB
	0.9254	 = Validation score   (accuracy)
	3.48s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=14, gpus=0, mem=0.0/10.9 GB
	Ensemble Weights: {'LightGBM': 1.0}
	0.9403	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 8.32s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 69114.2 rows/s (67 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (67 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_085705")
No path specified. Models will be saved in: "AutogluonModels/ag-20260422_085713"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.13.5
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.3.0: Wed Jan 28 20:48:41 PST 2026; root:xnu-12377.81.4~5/RELEASE_ARM64_T6041
CPU Count:          14
Pytorch Version:    2.9.1
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       10.94 GB / 36.00 GB (30.4%)
Disk Space Avail:   362.09 GB / 926.35 GB (39.1%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_085713"
Train Data Rows:    344
Train Data Columns: 5
Label Column:       species
Problem Type:       multiclass
Preprocessing data ...
Train Data Class Count: 3
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    11203.31 MB
	Train Data (Original)  Memory Usage: 0.03 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 4 | ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']
		('object', []) : 1 | ['island']
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) : 1 | ['island']
		('float', [])    : 4 | ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']
	0.0s = Fit runtime
	5 features in original data used to generate 5 features in processed data.
	Train Data (Processed) Memory Usage: 0.01 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.02s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 275, Val Rows: 69
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetFastAI ...
	Fitting with cpus=14, gpus=0, mem=0.0/10.9 GB
No improvement since epoch 6: early stopping
	0.9855	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...
	Fitting with cpus=14, gpus=0, mem=0.0/10.9 GB
	0.9855	 = Validation score   (accuracy)
	0.85s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	Fitting with cpus=14, gpus=0, mem=0.0/10.9 GB
	0.971	 = Validation score   (accuracy)
	1.45s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	Fitting with cpus=14, gpus=0
	0.9855	 = Validation score   (accuracy)
	0.15s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestEntr ...
	Fitting with cpus=14, gpus=0
	0.9855	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: CatBoost ...
	Fitting with cpus=14, gpus=0
	0.9855	 = Validation score   (accuracy)
	0.37s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	Fitting with cpus=14, gpus=0
	0.9855	 = Validation score   (accuracy)
	0.16s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	Fitting with cpus=14, gpus=0
	0.9855	 = Validation score   (accuracy)
	0.15s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: XGBoost ...
	Fitting with cpus=14, gpus=0
	0.9855	 = Validation score   (accuracy)
	0.71s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	Fitting with cpus=14, gpus=0, mem=0.0/10.9 GB
/Users/lamaalfreah/Desktop/AAI/.venv/lib/python3.13/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	0.9855	 = Validation score   (accuracy)
	0.29s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Fitting with cpus=14, gpus=0, mem=0.2/10.9 GB
	0.9855	 = Validation score   (accuracy)
	6.16s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=14, gpus=0, mem=0.0/11.4 GB
	Ensemble Weights: {'ExtraTreesGini': 1.0}
	0.9855	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.73s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 4591.7 rows/s (69 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_085713")