Name: Lama Alfreah.

# M4.Ex2: Penguins Classification (PyCaret)

- Run: [**Open In Colab**](https://colab.research.google.com/github/HassanAlgoz/B5/blob/main/content/W3/M6/exercises/ex2_pycaret_classification.ipynb)

## Exercise

Your task is to follow the steps outlined here, and apply them on the **Palmer Penguins Dataset** below:

- [**🚀 Classification**](https://pycaret.gitbook.io/docs/get-started/quickstart#classification)
    - Setup
    - Compare Models
    - Analyze Model
    - Predictions
    - Save the model

## Palmer Penguins Dataset

The goal of palmer penguins is to provide a great dataset for data exploration & visualization, as an alternative to iris.

The data contains 344 penguins. There are 3 different species of penguins in this dataset, collected from 3 islands in the Palmer Archipelago, Antarctica.

- Features: `4` numerical, `2` categorical
- Target: `species` (Categorical / 3 classes)
- Size: `344` samples
- Source: [Palmer Penguins](https://allisonhorst.github.io/palmerpenguins/)

### Load the data

In [1]:
import seaborn as sns

penguins = sns.load_dataset('penguins')
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

## Experiments

1. **First experiment**:
    - X = Flipper Length (numerical) & Bill Length (numerical)
    - y = Species (categorical)
2. **Second experiment**:
    - X = Weights (numerical) & Species (categorical)
    - y = Sex (categroical)
3. **Third experiment**:
    - X = `island`, `bill_length_mm`, `bill_depth_mm`, `flipper_length_mm`, `body_mass_g`
    - y = Sex and Species (multi-label classification)

### Spilt the data

In [2]:
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(
    penguins, test_size=0.2, random_state=42
)

### Training

### First experiment

In [3]:
from autogluon import *

from autogluon.tabular import TabularPredictor
exp1_data = train_data[["flipper_length_mm", "bill_length_mm", "species"]]

predictor_exp1 = TabularPredictor(
    label="species",
    problem_type="multiclass",
    eval_metric="accuracy"
).fit(
    exp1_data,
    presets='medium_quality_faster_train',
    time_limit= 60,
    excluded_model_types = ['NN_TORCH', 'FASTI'],
    num_cpus= 1,
    ag_args_fit ={'num_gpus' : 0}
)

No path specified. Models will be saved in: "AutogluonModels/ag-20260422_093828"
Preset alias specified: 'medium_quality_faster_train' maps to 'medium_quality'.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.13.5
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.3.0: Wed Jan 28 20:48:41 PST 2026; root:xnu-12377.81.4~5/RELEASE_ARM64_T6041
CPU Count:          14
Pytorch Version:    2.9.1
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       10.88 GB / 36.00 GB (30.2%)
Disk Space Avail:   361.98 GB / 926.35 GB (39.1%)
===================================================
Presets specified: ['medium_quality_faster_train']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "/Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_093828"
Train Data Rows:    275
Train Data Columns: 2
Label Column:       species
Problem Type:       multiclass
Preprocessing data ...
Train Data Class Count: 3
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    11140.41 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 2 | ['flipper_length_mm', 'bill_length_mm']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 2 | ['flipper_length_mm', 'bill_length_mm']
	0.0s = Fit runtime
	2 features in original data used to generate 2 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.01s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 220, Val Rows: 55
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Excluded models: ['NN_TORCH'] (Specified by `excluded_model_types`)
Fitting 10 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetFastAI ... Training model for up to 59.99s of the 59.99s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/10.9 GB
No improvement since epoch 2: early stopping
	0.9636	 = Validation score   (accuracy)
	0.35s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 59.63s of the 59.63s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/10.9 GB
	0.9455	 = Validation score   (accuracy)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 59.53s of the 59.53s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/10.9 GB
	0.9455	 = Validation score   (accuracy)
	0.08s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 59.46s of the 59.46s of remaining time.
	Fitting with cpus=1, gpus=0
	0.9455	 = Validation score   (accuracy)
	0.19s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 59.25s of the 59.25s of remaining time.
	Fitting with cpus=1, gpus=0
	0.9455	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 59.10s of the 59.10s of remaining time.
	Fitting with cpus=1, gpus=0
	0.9636	 = Validation score   (accuracy)
	0.18s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 58.91s of the 58.91s of remaining time.
	Fitting with cpus=1, gpus=0
	0.9455	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 58.75s of the 58.75s of remaining time.
	Fitting with cpus=1, gpus=0
	0.9455	 = Validation score   (accuracy)
	0.13s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 58.60s of the 58.60s of remaining time.
	Fitting with cpus=1, gpus=0
	0.9636	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 58.58s of the 58.58s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.2/11.1 GB
	0.9273	 = Validation score   (accuracy)
	0.11s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.99s of the 58.46s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=1, gpus=0, mem=0.0/11.1 GB
	Ensemble Weights: {'NeuralNetFastAI': 1.0}
	0.9636	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1.56s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 19689.9 rows/s (55 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_093828")

### Second experiment

In [8]:
exp2_data = train_data[["body_mass_g", "species", "sex"]].dropna()

predictor_exp2 = TabularPredictor(
    label="sex",
    problem_type="binary",
    eval_metric="accuracy"
).fit(
    exp2_data,
    presets='medium_quality_faster_train',
    time_limit= 60,
    excluded_model_types = ['NN_TORCH', 'FASTI'],
    num_cpus= 1,
    ag_args_fit ={'num_gpus' : 0}
)

pred_exp2 = predictor_exp2.predict(exp2_data.drop(columns=["sex"]))
predictor_exp2.leaderboard(exp2_data, silent=True)

No path specified. Models will be saved in: "AutogluonModels/ag-20260422_094328"
Preset alias specified: 'medium_quality_faster_train' maps to 'medium_quality'.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.13.5
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.3.0: Wed Jan 28 20:48:41 PST 2026; root:xnu-12377.81.4~5/RELEASE_ARM64_T6041
CPU Count:          14
Pytorch Version:    2.9.1
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       10.87 GB / 36.00 GB (30.2%)
Disk Space Avail:   361.97 GB / 926.35 GB (39.1%)
===================================================
Presets specified: ['medium_quality_faster_train']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "/Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_094328"
Train Data Rows:    267
Train Data Columns: 2
Label Column:       sex
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = Male, class 0 = Female
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (Male) vs negative (Female) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    11128.91 MB
	Train Data (Original)  Memory Usage: 0.02 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 1 | ['body_mass_g']
		('object', []) : 1 | ['species']
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) : 1 | ['species']
		('float', [])    : 1 | ['body_mass_g']
	0.0s = Fit runtime
	2 features in original data used to generate 2 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.02s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 213, Val Rows: 54
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Excluded models: ['NN_TORCH'] (Specified by `excluded_model_types`)
Fitting 10 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ... Training model for up to 59.98s of the 59.98s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/10.9 GB
	0.8704	 = Validation score   (accuracy)
	0.09s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 59.89s of the 59.89s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/10.9 GB
	0.8519	 = Validation score   (accuracy)
	0.09s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 59.80s of the 59.79s of remaining time.
	Fitting with cpus=1, gpus=0
	0.8333	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 59.64s of the 59.64s of remaining time.
	Fitting with cpus=1, gpus=0
	0.8333	 = Validation score   (accuracy)
	0.13s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 59.50s of the 59.49s of remaining time.
	Fitting with cpus=1, gpus=0
	0.8519	 = Validation score   (accuracy)
	0.17s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 59.32s of the 59.32s of remaining time.
	Fitting with cpus=1, gpus=0
	0.8333	 = Validation score   (accuracy)
	0.12s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 59.18s of the 59.18s of remaining time.
	Fitting with cpus=1, gpus=0
	0.8333	 = Validation score   (accuracy)
	0.12s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 59.05s of the 59.04s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/10.8 GB
No improvement since epoch 7: early stopping
	0.8519	 = Validation score   (accuracy)
	0.23s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 58.80s of the 58.80s of remaining time.
	Fitting with cpus=1, gpus=0
	0.8519	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 58.78s of the 58.78s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.1/10.8 GB
	0.8704	 = Validation score   (accuracy)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.98s of the 58.68s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=1, gpus=0, mem=0.0/10.8 GB
	Ensemble Weights: {'LightGBMXT': 1.0}
	0.8704	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1.35s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 52368.2 rows/s (54 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (54 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_094328")

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,LightGBMLarge,0.891386,0.870370,accuracy,0.001346,0.000719,0.095184,0.001346,0.000719,0.095184,1,True,10
1,ExtraTreesGini,0.887640,0.833333,accuracy,0.016238,0.014619,0.124307,0.016238,0.014619,0.124307,1,True,6
2,RandomForestEntr,0.887640,0.833333,accuracy,0.016554,0.012622,0.130004,0.016554,0.012622,0.130004,1,True,4
3,ExtraTreesEntr,0.887640,0.833333,accuracy,0.016697,0.012205,0.118525,0.016697,0.012205,0.118525,1,True,7
4,RandomForestGini,0.887640,0.833333,accuracy,0.027280,0.012746,0.136194,0.027280,0.012746,0.136194,1,True,3
5,LightGBM,0.880150,0.851852,accuracy,0.000682,0.000680,0.088788,0.000682,0.000680,0.088788,1,True,2
6,CatBoost,0.880150,0.851852,accuracy,0.001021,0.000456,0.166746,0.001021,0.000456,0.166746,1,True,5
7,XGBoost,0.876404,0.851852,accuracy,0.002640,0.001470,0.021137,0.002640,0.001470,0.021137,1,True,9
8,NeuralNetFastAI,0.876404,0.851852,accuracy,0.008966,0.002695,0.234669,0.008966,0.002695,0.234669,1,True,8
9,LightGBMXT,0.835206,0.870370,accuracy,0.000849,0.000793,0.093495,0.000849,0.000793,0.093495,1,True,1
10,WeightedEnsemble_L2,0.835206,0.870370,accuracy,0.001422,0.001031,0.109345,0.000573,0.000238,0.015850,2,True,11

### Third experiment

In [22]:
from MultilabelPredictor import MultilabelPredictor
exp3_data = train_data[[
    "island", "bill_length_mm", "bill_depth_mm",
    "flipper_length_mm", "body_mass_g", "sex", "species"
]].dropna()
labels = ['sex','species']  # which columns to predict based on the others
problem_types = ['binary','multiclass']  # type of each prediction problem (optional)
eval_metrics = ['accuracy','accuracy']  # metrics used to evaluate predictions for each label (optional)

multi_predictor = MultilabelPredictor(labels=labels, problem_types=problem_types, eval_metrics=eval_metrics)
multi_predictor.fit(
    exp3_data,
    presets='medium_quality_faster_train',
    time_limit= 60,
    excluded_model_types = ['NN_TORCH', 'FASTI'],
    num_cpus= 1,
    ag_args_fit ={'num_gpus' : 0}
    )

No path specified. Models will be saved in: "AutogluonModels/ag-20260422_101727"
Preset alias specified: 'medium_quality_faster_train' maps to 'medium_quality'.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.13.5
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.3.0: Wed Jan 28 20:48:41 PST 2026; root:xnu-12377.81.4~5/RELEASE_ARM64_T6041
CPU Count:          14
Pytorch Version:    2.9.1
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       10.50 GB / 36.00 GB (29.2%)
Disk Space Avail:   361.87 GB / 926.35 GB (39.1%)
===================================================
Presets specified: ['medium_quality_faster_train']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "/Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_101727/Predictor_sex"
Train Data Rows:    267
Train Data Columns: 5
Label Column:       sex
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = Male, class 0 = Female
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (Male) vs negative (Female) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10739.58 MB
	Train Data (Original)  Memory Usage: 0.02 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 4 | ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']
		('object', []) : 1 | ['island']
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) : 1 | ['island']
		('float', [])    : 4 | ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']
	0.0s = Fit runtime
	5 features in original data used to generate 5 features in processed data.
	Train Data (Processed) Memory Usage: 0.01 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.02s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 213, Val Rows: 54
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Excluded models: ['NN_TORCH'] (Specified by `excluded_model_types`)
Fitting 10 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ... Training model for up to 59.98s of the 59.98s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/10.5 GB

Fitting TabularPredictor for label: sex ...

	0.9074	 = Validation score   (accuracy)
	0.15s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 59.83s of the 59.82s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/10.5 GB
	0.9259	 = Validation score   (accuracy)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 59.69s of the 59.69s of remaining time.
	Fitting with cpus=1, gpus=0
	0.9259	 = Validation score   (accuracy)
	0.13s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 59.54s of the 59.53s of remaining time.
	Fitting with cpus=1, gpus=0
	0.9074	 = Validation score   (accuracy)
	0.15s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 59.37s of the 59.37s of remaining time.
	Fitting with cpus=1, gpus=0
	0.963	 = Validation score   (accuracy)
	0.21s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 59.16s of the 59.16s of remaining time.
	Fitting with cpus=1, gpus=0
	0.9444	 = Validation score   (accuracy)
	0.12s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 59.02s of the 59.02s of remaining time.
	Fitting with cpus=1, gpus=0
	0.9444	 = Validation score   (accuracy)
	0.13s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 58.86s of the 58.86s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/10.4 GB
	0.963	 = Validation score   (accuracy)
	0.26s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 58.60s of the 58.60s of remaining time.
	Fitting with cpus=1, gpus=0
	0.9259	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 58.58s of the 58.58s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.1/10.5 GB
	0.9444	 = Validation score   (accuracy)
	0.19s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.98s of the 58.37s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=1, gpus=0, mem=0.0/10.5 GB
	Ensemble Weights: {'CatBoost': 1.0}
	0.963	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1.65s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 74089.8 rows/s (54 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (54 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_101727/Predictor_sex")
Preset alias specified: 'medium_quality_faster_train' maps to 'medium_quality'.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.13.5
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.3.0: Wed Jan 28 20:48:41 PST 2026; root:xnu-12377.81.4~5/RELEASE_ARM64_T6041
CPU Count:          14
Pytorch Version:    2.9.1
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       10.47 GB / 36.00 GB (29.1%)
Disk Space Avail:   361.86 GB / 926.35 GB (39.1%)
===================================================
Presets specified: ['medium_quality_faster_train']
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ... Time limit = 60s
AutoGluon will save models to "/Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_101727/Predictor_species"
Train Data Rows:    267
Train Data Columns: 6
Label Column:       species
Problem Type:       multiclass
Preprocessing data ...
Train Data Class Count: 3
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10720.18 MB
	Train Data (Original)  Memory Usage: 0.04 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 4 | ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']
		('object', []) : 2 | ['island', 'sex']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 1 | ['island']
		('float', [])     : 4 | ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']
		('int', ['bool']) : 1 | ['sex']
	0.0s = Fit runtime
	6 features in original data used to generate 6 features in processed data.
	Train Data (Processed) Memory Usage: 0.01 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.03s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 213, Val Rows: 54
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Excluded models: ['NN_TORCH'] (Specified by `excluded_model_types`)
Fitting 10 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetFastAI ... Training model for up to 59.97s of the 59.97s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/10.5 GB

Fitting TabularPredictor for label: species ...

No improvement since epoch 4: early stopping
	1.0	 = Validation score   (accuracy)
	0.27s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 59.69s of the 59.69s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/10.6 GB
	1.0	 = Validation score   (accuracy)
	0.15s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 59.53s of the 59.53s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.0/10.6 GB
	1.0	 = Validation score   (accuracy)
	0.16s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 59.37s of the 59.37s of remaining time.
	Fitting with cpus=1, gpus=0
	0.9815	 = Validation score   (accuracy)
	0.15s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 59.20s of the 59.20s of remaining time.
	Fitting with cpus=1, gpus=0
	0.9815	 = Validation score   (accuracy)
	0.16s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 59.02s of the 59.02s of remaining time.
	Fitting with cpus=1, gpus=0
	0.9815	 = Validation score   (accuracy)
	0.27s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 58.75s of the 58.75s of remaining time.
	Fitting with cpus=1, gpus=0
	1.0	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 58.59s of the 58.59s of remaining time.
	Fitting with cpus=1, gpus=0
	1.0	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 58.44s of the 58.44s of remaining time.
	Fitting with cpus=1, gpus=0
	0.9815	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 58.41s of the 58.41s of remaining time.
	Fitting with cpus=1, gpus=0, mem=0.2/10.5 GB
	1.0	 = Validation score   (accuracy)
	0.2s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 59.97s of the 58.20s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=1, gpus=0, mem=0.0/10.5 GB
	Ensemble Weights: {'NeuralNetFastAI': 1.0}
	1.0	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1.84s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 18103.5 rows/s (54 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_101727/Predictor_species")

MultilabelPredictor saved to disk. Load with: MultilabelPredictor.load('/Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_101727')

### Monitoring

In [24]:
predictor_exp1. leaderboard()

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,CatBoost,0.963636,accuracy,0.000209,0.180463,0.000209,0.180463,1,True,6
1,XGBoost,0.963636,accuracy,0.000771,0.024057,0.000771,0.024057,1,True,9
2,NeuralNetFastAI,0.963636,accuracy,0.002566,0.346171,0.002566,0.346171,1,True,1
3,WeightedEnsemble_L2,0.963636,accuracy,0.002793,0.362052,0.000227,0.015881,2,True,11
4,LightGBMXT,0.945455,accuracy,0.000200,0.097744,0.000200,0.097744,1,True,2
5,LightGBM,0.945455,accuracy,0.000226,0.075745,0.000226,0.075745,1,True,3
6,RandomForestGini,0.945455,accuracy,0.013265,0.186616,0.013265,0.186616,1,True,4
7,ExtraTreesEntr,0.945455,accuracy,0.013664,0.131905,0.013664,0.131905,1,True,8
8,RandomForestEntr,0.945455,accuracy,0.014149,0.137195,0.014149,0.137195,1,True,5
9,ExtraTreesGini,0.945455,accuracy,0.014247,0.139225,0.014247,0.139225,1,True,7
10,LightGBMLarge,0.927273,accuracy,0.000219,0.107711,0.000219,0.107711,1,True,10

In [25]:
predictor_exp2. leaderboard()

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,LightGBMLarge,0.870370,accuracy,0.000719,0.095184,0.000719,0.095184,1,True,10
1,LightGBMXT,0.870370,accuracy,0.000793,0.093495,0.000793,0.093495,1,True,1
2,WeightedEnsemble_L2,0.870370,accuracy,0.001031,0.109345,0.000238,0.015850,2,True,11
3,CatBoost,0.851852,accuracy,0.000456,0.166746,0.000456,0.166746,1,True,5
4,LightGBM,0.851852,accuracy,0.000680,0.088788,0.000680,0.088788,1,True,2
5,XGBoost,0.851852,accuracy,0.001470,0.021137,0.001470,0.021137,1,True,9
6,NeuralNetFastAI,0.851852,accuracy,0.002695,0.234669,0.002695,0.234669,1,True,8
7,ExtraTreesEntr,0.833333,accuracy,0.012205,0.118525,0.012205,0.118525,1,True,7
8,RandomForestEntr,0.833333,accuracy,0.012622,0.130004,0.012622,0.130004,1,True,4
9,RandomForestGini,0.833333,accuracy,0.012746,0.136194,0.012746,0.136194,1,True,3
10,ExtraTreesGini,0.833333,accuracy,0.014619,0.124307,0.014619,0.124307,1,True,6

In [28]:
predictor_exp1.fit_summary(show_plot=True, verbosity=2)

*** Summary of fit() ***
Estimated performance of each model:
                  model  score_val eval_metric  pred_time_val  fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0              CatBoost   0.963636    accuracy       0.000209  0.180463                0.000209           0.180463            1       True          6
1               XGBoost   0.963636    accuracy       0.000771  0.024057                0.000771           0.024057            1       True          9
2       NeuralNetFastAI   0.963636    accuracy       0.002566  0.346171                0.002566           0.346171            1       True          1
3   WeightedEnsemble_L2   0.963636    accuracy       0.002793  0.362052                0.000227           0.015881            2       True         11
4            LightGBMXT   0.945455    accuracy       0.000200  0.097744                0.000200           0.097744            1       True          2
5              LightGBM   0.945455    accuracy       0.000226  0.075745                0.000226           0.075745            1       True          3
6      RandomForestGini   0.945455    accuracy       0.013265  0.186616                0.013265           0.186616            1       True          4
7        ExtraTreesEntr   0.945455    accuracy       0.013664  0.131905                0.013664           0.131905            1       True          8
8      RandomForestEntr   0.945455    accuracy       0.014149  0.137195                0.014149           0.137195            1       True          5
9        ExtraTreesGini   0.945455    accuracy       0.014247  0.139225                0.014247           0.139225            1       True          7
10        LightGBMLarge   0.927273    accuracy       0.000219  0.107711                0.000219           0.107711            1       True         10
Number of models trained: 11
Types of models trained:
{'NNFastAiTabularModel', 'RFModel', 'WeightedEnsembleModel', 'XTModel', 'LGBModel', 'XGBoostModel', 'CatBoostModel'}
Bagging used: False
Multi-layer stack-ensembling used: False
Feature Metadata (Processed):
(raw dtype, special dtypes):
('float', []) : 2 | ['flipper_length_mm', 'bill_length_mm']
Plot summary of models saved to file: /Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_093828/SummaryOfModels.html
*** End of fit() summary ***

{'model_types': {'NeuralNetFastAI': 'NNFastAiTabularModel',
  'LightGBMXT': 'LGBModel',
  'LightGBM': 'LGBModel',
  'RandomForestGini': 'RFModel',
  'RandomForestEntr': 'RFModel',
  'CatBoost': 'CatBoostModel',
  'ExtraTreesGini': 'XTModel',
  'ExtraTreesEntr': 'XTModel',
  'XGBoost': 'XGBoostModel',
  'LightGBMLarge': 'LGBModel',
  'WeightedEnsemble_L2': 'WeightedEnsembleModel'},
 'model_performance': {'NeuralNetFastAI': 0.9636363636363636,
  'LightGBMXT': 0.9454545454545454,
  'LightGBM': 0.9454545454545454,
  'RandomForestGini': 0.9454545454545454,
  'RandomForestEntr': 0.9454545454545454,
  'CatBoost': 0.9636363636363636,
  'ExtraTreesGini': 0.9454545454545454,
  'ExtraTreesEntr': 0.9454545454545454,
  'XGBoost': 0.9636363636363636,
  'LightGBMLarge': 0.9272727272727272,
  'WeightedEnsemble_L2': 0.9636363636363636},
 'model_best': 'WeightedEnsemble_L2',
 'model_paths': {'NeuralNetFastAI': ['NeuralNetFastAI'],
  'LightGBMXT': ['LightGBMXT'],
  'LightGBM': ['LightGBM'],
  'RandomForestGini': ['RandomForestGini'],
  'RandomForestEntr': ['RandomForestEntr'],
  'CatBoost': ['CatBoost'],
  'ExtraTreesGini': ['ExtraTreesGini'],
  'ExtraTreesEntr': ['ExtraTreesEntr'],
  'XGBoost': ['XGBoost'],
  'LightGBMLarge': ['LightGBMLarge'],
  'WeightedEnsemble_L2': ['WeightedEnsemble_L2']},
 'model_fit_times': {'NeuralNetFastAI': 0.34617090225219727,
  'LightGBMXT': 0.09774398803710938,
  'LightGBM': 0.0757451057434082,
  'RandomForestGini': 0.1866159439086914,
  'RandomForestEntr': 0.13719511032104492,
  'CatBoost': 0.18046307563781738,
  'ExtraTreesGini': 0.13922476768493652,
  'ExtraTreesEntr': 0.13190507888793945,
  'XGBoost': 0.024056673049926758,
  'LightGBMLarge': 0.1077110767364502,
  'WeightedEnsemble_L2': 0.01588129997253418},
 'model_pred_times': {'NeuralNetFastAI': 0.0025663375854492188,
  'LightGBMXT': 0.00020003318786621094,
  'LightGBM': 0.00022602081298828125,
  'RandomForestGini': 0.013264894485473633,
  'RandomForestEntr': 0.014149188995361328,
  'CatBoost': 0.0002090930938720703,
  'ExtraTreesGini': 0.01424717903137207,
  'ExtraTreesEntr': 0.013663768768310547,
  'XGBoost': 0.0007710456848144531,
  'LightGBMLarge': 0.00021886825561523438,
  'WeightedEnsemble_L2': 0.0002269744873046875},
 'num_bag_folds': 0,
 'max_stack_level': 2,
 'num_classes': 3,
 'model_hyperparams': {'NeuralNetFastAI': {'layers': None,
   'emb_drop': 0.1,
   'ps': 0.1,
   'bs': 'auto',
   'lr': 0.01,
   'epochs': 'auto',
   'early.stopping.min_delta': 0.0001,
   'early.stopping.patience': 20,
   'smoothing': 0.0,
   'random_seed': 0},
  'LightGBMXT': {'learning_rate': 0.05, 'extra_trees': True, 'seed': 0},
  'LightGBM': {'learning_rate': 0.05, 'seed': 0},
  'RandomForestGini': {'n_estimators': 300,
   'max_leaf_nodes': 15000,
   'n_jobs': -1,
   'bootstrap': True,
   'criterion': 'gini',
   'random_state': 0},
  'RandomForestEntr': {'n_estimators': 300,
   'max_leaf_nodes': 15000,
   'n_jobs': -1,
   'bootstrap': True,
   'criterion': 'entropy',
   'random_state': 0},
  'CatBoost': {'iterations': 10000,
   'learning_rate': 0.05,
   'allow_writing_files': False,
   'eval_metric': 'Accuracy',
   'random_seed': 0},
  'ExtraTreesGini': {'n_estimators': 300,
   'max_leaf_nodes': 15000,
   'n_jobs': -1,
   'bootstrap': True,
   'criterion': 'gini',
   'random_state': 0},
  'ExtraTreesEntr': {'n_estimators': 300,
   'max_leaf_nodes': 15000,
   'n_jobs': -1,
   'bootstrap': True,
   'criterion': 'entropy',
   'random_state': 0},
  'XGBoost': {'n_estimators': 10000,
   'learning_rate': 0.1,
   'n_jobs': -1,
   'proc.max_category_levels': 100,
   'objective': 'multi:softprob',
   'booster': 'gbtree',
   'num_class': 3,
   'seed': 0},
  'LightGBMLarge': {'learning_rate': 0.03,
   'num_leaves': 128,
   'feature_fraction': 0.9,
   'min_data_in_leaf': 3,
   'seed': 0},
  'WeightedEnsemble_L2': {'use_orig_features': False,
   'valid_stacker': True,
   'max_base_models': 0,
   'max_base_models_per_type': 'auto',
   'save_bag_folds': True,
   'stratify': 'auto',
   'bin': 'auto',
   'n_bins': None,
   'vary_seed_across_folds': False,
   'model_random_seed': 0}},
 'leaderboard':                   model  score_val eval_metric  pred_time_val  fit_time  \
 0              CatBoost   0.963636    accuracy       0.000209  0.180463
 1               XGBoost   0.963636    accuracy       0.000771  0.024057
 2       NeuralNetFastAI   0.963636    accuracy       0.002566  0.346171
 3   WeightedEnsemble_L2   0.963636    accuracy       0.002793  0.362052
 4            LightGBMXT   0.945455    accuracy       0.000200  0.097744
 5              LightGBM   0.945455    accuracy       0.000226  0.075745
 6      RandomForestGini   0.945455    accuracy       0.013265  0.186616
 7        ExtraTreesEntr   0.945455    accuracy       0.013664  0.131905
 8      RandomForestEntr   0.945455    accuracy       0.014149  0.137195
 9        ExtraTreesGini   0.945455    accuracy       0.014247  0.139225
 10        LightGBMLarge   0.927273    accuracy       0.000219  0.107711

     pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  \
 0                 0.000209           0.180463            1       True
 1                 0.000771           0.024057            1       True
 2                 0.002566           0.346171            1       True
 3                 0.000227           0.015881            2       True
 4                 0.000200           0.097744            1       True
 5                 0.000226           0.075745            1       True
 6                 0.013265           0.186616            1       True
 7                 0.013664           0.131905            1       True
 8                 0.014149           0.137195            1       True
 9                 0.014247           0.139225            1       True
 10                0.000219           0.107711            1       True

     fit_order
 0           6
 1           9
 2           1
 3          11
 4           2
 5           3
 6           4
 7           8
 8           5
 9           7
 10         10  }

In [29]:
predictor_exp2.fit_summary(show_plot=True, verbosity=2)

*** Summary of fit() ***
Estimated performance of each model:
                  model  score_val eval_metric  pred_time_val  fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0         LightGBMLarge   0.870370    accuracy       0.000719  0.095184                0.000719           0.095184            1       True         10
1            LightGBMXT   0.870370    accuracy       0.000793  0.093495                0.000793           0.093495            1       True          1
2   WeightedEnsemble_L2   0.870370    accuracy       0.001031  0.109345                0.000238           0.015850            2       True         11
3              CatBoost   0.851852    accuracy       0.000456  0.166746                0.000456           0.166746            1       True          5
4              LightGBM   0.851852    accuracy       0.000680  0.088788                0.000680           0.088788            1       True          2
5               XGBoost   0.851852    accuracy       0.001470  0.021137                0.001470           0.021137            1       True          9
6       NeuralNetFastAI   0.851852    accuracy       0.002695  0.234669                0.002695           0.234669            1       True          8
7        ExtraTreesEntr   0.833333    accuracy       0.012205  0.118525                0.012205           0.118525            1       True          7
8      RandomForestEntr   0.833333    accuracy       0.012622  0.130004                0.012622           0.130004            1       True          4
9      RandomForestGini   0.833333    accuracy       0.012746  0.136194                0.012746           0.136194            1       True          3
10       ExtraTreesGini   0.833333    accuracy       0.014619  0.124307                0.014619           0.124307            1       True          6
Number of models trained: 11
Types of models trained:
{'NNFastAiTabularModel', 'RFModel', 'WeightedEnsembleModel', 'XTModel', 'LGBModel', 'XGBoostModel', 'CatBoostModel'}
Bagging used: False
Multi-layer stack-ensembling used: False
Feature Metadata (Processed):
(raw dtype, special dtypes):
('category', []) : 1 | ['species']
('float', [])    : 1 | ['body_mass_g']
Plot summary of models saved to file: /Users/lamaalfreah/Desktop/AAI/student/c3/AutogluonModels/ag-20260422_094328/SummaryOfModels.html
*** End of fit() summary ***

{'model_types': {'LightGBMXT': 'LGBModel',
  'LightGBM': 'LGBModel',
  'RandomForestGini': 'RFModel',
  'RandomForestEntr': 'RFModel',
  'CatBoost': 'CatBoostModel',
  'ExtraTreesGini': 'XTModel',
  'ExtraTreesEntr': 'XTModel',
  'NeuralNetFastAI': 'NNFastAiTabularModel',
  'XGBoost': 'XGBoostModel',
  'LightGBMLarge': 'LGBModel',
  'WeightedEnsemble_L2': 'WeightedEnsembleModel'},
 'model_performance': {'LightGBMXT': 0.8703703703703703,
  'LightGBM': 0.8518518518518519,
  'RandomForestGini': 0.8333333333333334,
  'RandomForestEntr': 0.8333333333333334,
  'CatBoost': 0.8518518518518519,
  'ExtraTreesGini': 0.8333333333333334,
  'ExtraTreesEntr': 0.8333333333333334,
  'NeuralNetFastAI': 0.8518518518518519,
  'XGBoost': 0.8518518518518519,
  'LightGBMLarge': 0.8703703703703703,
  'WeightedEnsemble_L2': 0.8703703703703703},
 'model_best': 'WeightedEnsemble_L2',
 'model_paths': {'LightGBMXT': ['LightGBMXT'],
  'LightGBM': ['LightGBM'],
  'RandomForestGini': ['RandomForestGini'],
  'RandomForestEntr': ['RandomForestEntr'],
  'CatBoost': ['CatBoost'],
  'ExtraTreesGini': ['ExtraTreesGini'],
  'ExtraTreesEntr': ['ExtraTreesEntr'],
  'NeuralNetFastAI': ['NeuralNetFastAI'],
  'XGBoost': ['XGBoost'],
  'LightGBMLarge': ['LightGBMLarge'],
  'WeightedEnsemble_L2': ['WeightedEnsemble_L2']},
 'model_fit_times': {'LightGBMXT': 0.09349489212036133,
  'LightGBM': 0.08878827095031738,
  'RandomForestGini': 0.13619399070739746,
  'RandomForestEntr': 0.1300041675567627,
  'CatBoost': 0.16674590110778809,
  'ExtraTreesGini': 0.12430691719055176,
  'ExtraTreesEntr': 0.11852502822875977,
  'NeuralNetFastAI': 0.23466897010803223,
  'XGBoost': 0.021136760711669922,
  'LightGBMLarge': 0.0951838493347168,
  'WeightedEnsemble_L2': 0.015850067138671875},
 'model_pred_times': {'LightGBMXT': 0.0007929801940917969,
  'LightGBM': 0.0006802082061767578,
  'RandomForestGini': 0.012746095657348633,
  'RandomForestEntr': 0.012621641159057617,
  'CatBoost': 0.0004563331604003906,
  'ExtraTreesGini': 0.014619112014770508,
  'ExtraTreesEntr': 0.012205123901367188,
  'NeuralNetFastAI': 0.0026950836181640625,
  'XGBoost': 0.0014698505401611328,
  'LightGBMLarge': 0.0007190704345703125,
  'WeightedEnsemble_L2': 0.00023818016052246094},
 'num_bag_folds': 0,
 'max_stack_level': 2,
 'num_classes': 2,
 'model_hyperparams': {'LightGBMXT': {'learning_rate': 0.05,
   'extra_trees': True,
   'seed': 0},
  'LightGBM': {'learning_rate': 0.05, 'seed': 0},
  'RandomForestGini': {'n_estimators': 300,
   'max_leaf_nodes': 15000,
   'n_jobs': -1,
   'bootstrap': True,
   'criterion': 'gini',
   'random_state': 0},
  'RandomForestEntr': {'n_estimators': 300,
   'max_leaf_nodes': 15000,
   'n_jobs': -1,
   'bootstrap': True,
   'criterion': 'entropy',
   'random_state': 0},
  'CatBoost': {'iterations': 10000,
   'learning_rate': 0.05,
   'allow_writing_files': False,
   'eval_metric': 'Accuracy',
   'random_seed': 0},
  'ExtraTreesGini': {'n_estimators': 300,
   'max_leaf_nodes': 15000,
   'n_jobs': -1,
   'bootstrap': True,
   'criterion': 'gini',
   'random_state': 0},
  'ExtraTreesEntr': {'n_estimators': 300,
   'max_leaf_nodes': 15000,
   'n_jobs': -1,
   'bootstrap': True,
   'criterion': 'entropy',
   'random_state': 0},
  'NeuralNetFastAI': {'layers': None,
   'emb_drop': 0.1,
   'ps': 0.1,
   'bs': 'auto',
   'lr': 0.01,
   'epochs': 'auto',
   'early.stopping.min_delta': 0.0001,
   'early.stopping.patience': 20,
   'smoothing': 0.0,
   'random_seed': 0},
  'XGBoost': {'n_estimators': 10000,
   'learning_rate': 0.1,
   'n_jobs': -1,
   'proc.max_category_levels': 100,
   'objective': 'binary:logistic',
   'booster': 'gbtree',
   'seed': 0},
  'LightGBMLarge': {'learning_rate': 0.03,
   'num_leaves': 128,
   'feature_fraction': 0.9,
   'min_data_in_leaf': 3,
   'seed': 0},
  'WeightedEnsemble_L2': {'use_orig_features': False,
   'valid_stacker': True,
   'max_base_models': 0,
   'max_base_models_per_type': 'auto',
   'save_bag_folds': True,
   'stratify': 'auto',
   'bin': 'auto',
   'n_bins': None,
   'vary_seed_across_folds': False,
   'model_random_seed': 0}},
 'leaderboard':                   model  score_val eval_metric  pred_time_val  fit_time  \
 0         LightGBMLarge   0.870370    accuracy       0.000719  0.095184
 1            LightGBMXT   0.870370    accuracy       0.000793  0.093495
 2   WeightedEnsemble_L2   0.870370    accuracy       0.001031  0.109345
 3              CatBoost   0.851852    accuracy       0.000456  0.166746
 4              LightGBM   0.851852    accuracy       0.000680  0.088788
 5               XGBoost   0.851852    accuracy       0.001470  0.021137
 6       NeuralNetFastAI   0.851852    accuracy       0.002695  0.234669
 7        ExtraTreesEntr   0.833333    accuracy       0.012205  0.118525
 8      RandomForestEntr   0.833333    accuracy       0.012622  0.130004
 9      RandomForestGini   0.833333    accuracy       0.012746  0.136194
 10       ExtraTreesGini   0.833333    accuracy       0.014619  0.124307

     pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  \
 0                 0.000719           0.095184            1       True
 1                 0.000793           0.093495            1       True
 2                 0.000238           0.015850            2       True
 3                 0.000456           0.166746            1       True
 4                 0.000680           0.088788            1       True
 5                 0.001470           0.021137            1       True
 6                 0.002695           0.234669            1       True
 7                 0.012205           0.118525            1       True
 8                 0.012622           0.130004            1       True
 9                 0.012746           0.136194            1       True
 10                0.014619           0.124307            1       True

     fit_order
 0          10
 1           1
 2          11
 3           5
 4           2
 5           9
 6           8
 7           7
 8           4
 9           3
 10          6  }

In [31]:
predictor_exp1.feature_importance(test_data)

These features in provided data are not utilized by the predictor and will be ignored: ['island', 'bill_depth_mm', 'body_mass_g', 'sex']
Computing feature importance via permutation shuffling for 2 features using 69 rows with 5 shuffle sets...
	0.25s	= Expected runtime (0.05s per shuffle set)
	0.06s	= Actual runtime (Completed 5 of 5 shuffle sets)

                   importance    stddev   p_value  n  p99_high   p99_low
flipper_length_mm    0.356522  0.041753  0.000022  5  0.442492  0.270551
bill_length_mm       0.330435  0.037514  0.000020  5  0.407676  0.253194

### Predicting

In [34]:
# Predict for each row
predictor_exp1.predict(test_data)

194    Chinstrap
157    Chinstrap
225       Gentoo
208    Chinstrap
318    Chinstrap
         ...
321       Gentoo
172       Adelie
73     Chinstrap
76        Adelie
16        Adelie
Name: species, Length: 69, dtype: object

In [36]:
# Predict for each row
predictor_exp2.predict(test_data)

194    Female
157      Male
225    Female
208    Female
318    Female
        ...
321      Male
172    Female
73       Male
76     Female
16     Female
Name: sex, Length: 69, dtype: object